### ISSUE TITLE
"read_from_folder" cannot read files if the textgrid file includes a tier with no points

### ISSUE THREAD

**Issue by ShungoSuzuki** [agricolamz/phonfieldwork#34]
"read_from_folder" cannot read files if the textgrid file that includes a tier with no points, and as a result, the whole textgrid file could not be read and is replaced with NA. 

Zero point is actually important information in analysis; so I wonder if someone could show the solution to this problem.

**Comment by oliverehmer** [comment]
Dear Shungo,

thank you for your message.

Unfortunately I cannot reproduce the error.

The function to load "TextGrids" in the act package is "act::import_textgrid()" or "act::corpus:new()" (there is no function 'read_from_folder').

Could you please provide a TextGrid that results in the mentioned error?

All the best,
Oliver

__________________________________________________

PD Dr. Oliver Ehmer
Albert-Ludwigs-Universität Freiburg im Breisgau, Romanisches Seminar
Platz der Universität 3, Raum 1275, D-79098 Freiburg

+49 (761) 203-97676
www.oliverehmer.de <http://www.oliverehmer.de/>
www.body-knowledge.org <http://www.body-knowledge.org/>

**Comment by ShungoSuzuki** [comment]
Dear Oliver,

Thanks for the reply! I used the read_from_folder" function in the "phonfieldwork" package; I might have used the older version of the package, perhaps...?
Anyway, I'm copying the error message below, and you can download the TextGrid file that I used from here: https://www.dropbox.com/sh/ur8f6x60mokcus1/AABhkYZblHZ4ffZ2wxF2SaXGa?dl=0

I'd appreciate if you could suggest some solution to this; I need to read multiple TextGrid files from a folder and to merge them into a single dataframe...

Shungo
####################
Warning messages:
1: In value[[3L]](cond) :
  Error while reading from /Users/suzukis/Dropbox/PhD_Lancaster/ResearchTool/PauseSegmentation/Example/2001_Arg_Lib.TextGrid:
wrong sign in 'by' argument

2: In value[[3L]](cond) :
  Error while reading from /Users/suzukis/Dropbox/PhD_Lancaster/ResearchTool/PauseSegmentation/Example/2002_Arg_Lib.TextGrid:
wrong sign in 'by' argument

**Comment by agricolamz** [comment]
Dear Shungo (@ShungoSuzuki),

thank you for opening an issue. Indeed you are right, it was my mistake, but I think, I corrected it and tested with files that you kindly provided. For now my package ignores empty tiers in textgrids (that could be sad, if there is something coded with tier names).

If you do not need any information coded with tier names, you can simply install the development version of the package:

```
install.packages("remotes")
remotes::install_github("ropensci/phonfieldwork")
```

and then rerun all your code. In close future it will be available from CRAN.

If you need information coded with tier names, then Oliver's (@oliverehmer) `act` package could come in handy:

```
> library(act)
> t <- import_textgrid("~/Desktop/test/2001_Arg_Lib.TextGrid")
> t@tiers

                 name         type position
Transcript Transcript IntervalTier        1
silences     silences IntervalTier        2
Filled         Filled     TextTier        3
Dysflu         Dysflu     TextTier        4
Rep               Rep     TextTier        5
Self             Self     TextTier        6
False           False     TextTier        7
```

Please let me know, if this solves an issue.

All the best,
GM

**Comment by ShungoSuzuki** [comment]
Dear GM,

Thanks very much for creating the revised version, but I've got the same error message...
Could you please check if the function of "read_from_folder" would work in your revised package...? I might have done something wrong with downloading the revised one, though...

Warning messages:
1: In value[[3L]](cond) :
  Error while reading from /Users/suzukis/Dropbox/PhD_Lancaster/ResearchTool/PauseSegmentation/Example/2001_Arg_Lib.TextGrid:
wrong sign in 'by' argument

**Comment by agricolamz** [comment]
Dear Shungo,

yes, it works on my computer. Are you sure that you've downloaded the newest version (as code below shows, it should be v. 0.0.11)?

```
> library(phonfieldwork)
> packageVersion("phonfieldwork")
[1] ‘0.0.11’
> t <- read_from_folder("~/Desktop/test/", type = "textgrid")
> str(t)
'data.frame':	171 obs. of  7 variables:
 $ id        : num  1 1 2 3 4 5 2 6 1 3 ...
 $ time_start: num  0 0 0.737 0.917 1.205 ...
 $ time_end  : num  2.02 0.737 0.917 1.205 1.369 ...
 $ content   : chr  "I'm against this statement" "" "CI" "" ...
 $ tier      : num  1 2 2 2 2 2 1 2 3 1 ...
 $ tier_name : chr  "Transcript" "silences" "silences" "silences" ...
 $ source    : chr  "2001_Arg_Lib.TextGrid" "2001_Arg_Lib.TextGrid" "2001_Arg_Lib.TextGrid" "2001_Arg_Lib.TextGrid" ...
 ```

**Comment by ShungoSuzuki** [comment]
Dear GM,

As you guessed, the version on my laptop is still the older one, although I used the code you put above to download the package. Is it possible that the version uploaded on the GitHub has not yet reflected for users other than an uploader? Otherwise, do you know another way of sharing the updated version of the package...?

Shungo

> packageVersion("phonfieldwork")
[1] ‘0.0.10’

**Comment by agricolamz** [comment]
Oh, sorry, it appears that I forgot to update it here. Could you try again?

**Comment by ShungoSuzuki** [comment]
Now the problem has been solved! Thank you very much for working on my problem very efficiently and kindly!
Many thanks,
Shungo

**Comment by oliverehmer** [comment]
Dear both,
sorry for creating confusion. I am new to GitHub and wrongly assumed that you, Shungo, referred to my act package. Only now I realize that you were using phonfieldwork.

Anyway, in case you want to try the act package, you can use this code:
path <- '/Users/oliverehmer/Downloads/Example'
x <- act::corpus_new(pathsAnnotationFiles = path, pathsMediaFiles = path)
x@transcripts
x@transcripts[[1]]@tiers
x@transcripts[[1]]@annotations

I'll take more care next time!

Al the best,
Oliver

**Comment by agricolamz** [comment]
No, worries, Oliver! Happy to have you here!
