### ISSUE TITLE
Fix pkgdown reference index

### ISSUE THREAD

**Issue by maelle** [agricolamz/phonfieldwork#46]
:wave: @agricolamz!

The pkgdown build for your package is currently failing because some of the documentation topics are missing from the pkgdown config file. Could you please fix?

```r
> pkgdown::check_pkgdown()
Error in `check_missing_topics()`:
! All topics must be included in reference index
• Missing topics: add_leading_symbols, create_image_look_up, create_sound_play, create_viewer, df_to_eaf, df_to_exb, remove_textgrid_tier
```

**Comment by maelle** [comment]
Note that for topics you do not want to include in the index you can create an "internal" section https://pkgdown.r-lib.org/reference/build_reference.html?q=internal#missing-topics

**Comment by maelle** [comment]
To check all topics are listed, after editing the configuration file you can run `pkgdown::check_pkgdown()`.

**Comment by maelle** [comment]
wave @agricolamz! Friendly reminder :smile_cat:

**Comment by agricolamz** [comment]
Dear @maelle, I've seen the problem, but I will be able to react only in mid September. Sorry...

**Comment by maelle** [comment]
:wave: @agricolamz! Friendly reminder :smile:

**Comment by agricolamz** [comment]
@maelle, thank you, I guess now it is fine!

**Comment by maelle** [comment]
Yes, thank you!
